"""add_timezone_column_to_users

Revision ID: 22c585d00c5f
Revises: 46994e5e94b4
Create Date: 2025-08-08 00:22:15.305995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c585d00c5f'
down_revision: Union[str, Sequence[str], None] = '46994e5e94b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_ip_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_ip_address')
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###
