"""Initial tables

Revision ID: 641b0287bfe4
Revises: 
Create Date: 2025-07-21 10:19:37.644306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641b0287bfe4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('invoice_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.add_column('chat_history', sa.Column('chat_session_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_chat_history_chat_session_id'), 'chat_history', ['chat_session_id'], unique=False)
    op.add_column('user_subscriptions', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('cancel_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'cancel_at')
    op.drop_column('user_subscriptions', 'stripe_subscription_id')
    op.drop_column('user_subscriptions', 'stripe_customer_id')
    op.drop_index(op.f('ix_chat_history_chat_session_id'), table_name='chat_history')
    op.drop_column('chat_history', 'chat_session_id')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
