"""reupdate user subscription table

Revision ID: 6591d50e567a
Revises: 887c6839739b
Create Date: 2025-08-14 19:54:39.290707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6591d50e567a'
down_revision: Union[str, Sequence[str], None] = '887c6839739b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subscriptions', 'plan_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subscriptions', 'plan_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
