"""Add public chat sharing tables

Revision ID: 7617b56e0e7b
Revises: 22c585d00c5f
Create Date: 2025-08-11 11:04:20.125237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7617b56e0e7b'
down_revision: Union[str, Sequence[str], None] = '22c585d00c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_chat_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chat_session_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('share_token', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('allow_download', sa.Boolean(), nullable=True),
    sa.Column('password_protected', sa.Boolean(), nullable=True),
    sa.Column('access_password', sa.String(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('max_views', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_chat_shares_chat_session_id'), 'public_chat_shares', ['chat_session_id'], unique=False)
    op.create_index(op.f('ix_public_chat_shares_id'), 'public_chat_shares', ['id'], unique=False)
    op.create_index(op.f('ix_public_chat_shares_share_token'), 'public_chat_shares', ['share_token'], unique=True)
    op.create_table('public_chat_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('share_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['share_id'], ['public_chat_shares.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_chat_views_id'), 'public_chat_views', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_chat_views_id'), table_name='public_chat_views')
    op.drop_table('public_chat_views')
    op.drop_index(op.f('ix_public_chat_shares_share_token'), table_name='public_chat_shares')
    op.drop_index(op.f('ix_public_chat_shares_id'), table_name='public_chat_shares')
    op.drop_index(op.f('ix_public_chat_shares_chat_session_id'), table_name='public_chat_shares')
    op.drop_table('public_chat_shares')
    # ### end Alembic commands ###
