"""user_subscription update

Revision ID: 887c6839739b
Revises: 7617b56e0e7b
Create Date: 2025-08-14 18:24:24.212203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '887c6839739b'
down_revision: Union[str, Sequence[str], None] = '7617b56e0e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_subscriptions', sa.Column('last_payment_check', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_subscriptions', sa.Column('auto_debit_enabled', sa.Boolean(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'current_period_end')
    op.drop_column('user_subscriptions', 'auto_debit_enabled')
    op.drop_column('user_subscriptions', 'last_payment_check')
    op.drop_column('user_subscriptions', 'subscription_end_date')
    op.drop_column('user_subscriptions', 'subscription_status')
    # ### end Alembic commands ###
