"""add swot analysis cols in document table

Revision ID: 88ab075244d0
Revises: 5e38007e9fa2
Create Date: 2025-07-31 16:20:09.485833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ab075244d0'
down_revision: Union[str, Sequence[str], None] = '5e38007e9fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('swot_analysis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'swot_analysis')
    # ### end Alembic commands ###
