"""add impact

Revision ID: d2c3dbfa5463
Revises: e0825bb3dc06
Create Date: 2025-08-24 17:43:23.112758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c3dbfa5463'
down_revision: Union[str, Sequence[str], None] = 'e0825bb3dc06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('impact', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'impact')
    # ### end Alembic commands ###
