"""edit feedback table

Revision ID: d5257abd1e2b
Revises: 1aca6c0a5ea2
Create Date: 2025-08-15 23:53:43.417759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5257abd1e2b'
down_revision: Union[str, Sequence[str], None] = '1aca6c0a5ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('feedback_category', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('feedback_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'feedback_type')
    op.drop_column('feedback', 'feedback_category')
    # ### end Alembic commands ###
