"""add 2 columns for problem and recommendations

Revision ID: e0825bb3dc06
Revises: d5257abd1e2b
Create Date: 2025-08-21 13:41:01.753543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0825bb3dc06'
down_revision: Union[str, Sequence[str], None] = 'd5257abd1e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('problem_context', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('recommendations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'recommendations')
    op.drop_column('documents', 'problem_context')
    # ### end Alembic commands ###
